#!/bin/sh

MODULE=$1
BASE_PACKAGE=$2

DPKG=/usr/bin/dpkg
DEBPATH=/var/lib/jolicloud-hardware/repo-cache
CONFIGPATH=/usr/lib/jolicloud-hardware/config

if [ $# -lt 2 ]; then
    exit 1
fi

err=0

if `$DPKG --get-selections $BASE_PACKAGE 2>/dev/null | grep -q \[^de\]install`; then
    echo "Already installed $MODULE package $BASE_PACKAGE.";
    #exit 0;
else
    if [ -d $DEBPATH/$BASE_PACKAGE ]; then
        echo "Installing $MODULE package $BASE_PACKAGE.";
        message=
        if grep -q "boot=casper" /proc/cmdline; then
            message="Please wait, pre-configuring ATI driver..."
        else
            message="Please wait, finalizing ATI driver installation..."
        fi
        plymouth message --text="$message"
        $DPKG -i $DEBPATH/$BASE_PACKAGE/*
        err=$?

        if [ $? -eq 0 -a -x /usr/lib/fglrx/bin/aticonfig ]; then
            /usr/lib/fglrx/bin/aticonfig --initial -f
            /usr/lib/fglrx/bin/aticonfig --overlay-type=Xv
            err=$?
        fi

        plymouth message --text="Continuing boot process..."
    fi
fi

exit $err
