#!/bin/sh

MODULE=$1
BASE_PACKAGE=$2

DPKG=/usr/bin/dpkg
DEBPATH=/var/lib/jolicloud-hardware/repo-cache
CONFIGPATH=/usr/lib/jolicloud-hardware/config

if [ $# -lt 2 ]; then
    exit 1
fi

if `$DPKG --get-selections $BASE_PACKAGE 2>/dev/null | grep -q \[^de\]install`; then
    echo "Already installed $MODULE package $BASE_PACKAGE.";
    #exit 0;
else
    if [ -d $DEBPATH/$MODULE ]; then
        echo "Installing $MODULE package $BASE_PACKAGE.";
        usplash_write "TIMEOUT 120"
        #usplash_write "VERBOSE ON"
        usplash_write "TEXT Please wait, initializing nVidia driver..."
        usplash_write "PULSATE"
        $DPKG -i $DEBPATH/$MODULE/*
        usplash_write "TEXT Finished."
        usplash_write "VERBOSE default"
        usplash_write "TIMEOUT 15"
    fi
fi

if [ -x $CONFIGPATH/config-xorg-$MODULE.py ]; then
    echo "Running $MODULE configuration package.";
    $CONFIGPATH/config-xorg-$MODULE.py
fi

exit 0
