#!/bin/sh

MODULE=$1
BASE_PACKAGE=$2

DPKG=/usr/bin/dpkg
DEBPATH=/var/lib/jolicloud-hardware/repo-cache
CONFIGPATH=/usr/lib/jolicloud-hardware/config

if [ $# -lt 2 ]; then
    exit 1
fi

err=0

if `$DPKG --get-selections $BASE_PACKAGE 2>/dev/null | grep -q \[^de\]install`; then
    echo "Already installed $MODULE package $BASE_PACKAGE.";
    #exit 0;
else
    if [ -d $DEBPATH/$MODULE ]; then
        echo "Installing $MODULE package $BASE_PACKAGE.";
        plymouth message --text="Please wait, initializing Poulsbo driver..."
        $DPKG -i $DEBPATH/$MODULE/*
        err=$?
        plymouth message --text="Continuing boot process..."
    fi
fi

# Xorg configuration is now handled by pouslbo-config package.

exit $err
